name: Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Download svg
        run: |
          curl -o assets/stats.svg "https://github-readme-stats-beryl-one.vercel.app/api?username=ttytm&count_private=true&line_height=32&role=owner,collaborator&show=reviews,discussions_answered&show_icons=true&theme=github_dark_dimmed"
          curl -o assets/langs.svg "https://github-readme-stats-beryl-one.vercel.app/api/top-langs/?username=ttytm&layout=compact&role=owner,collaborator&langs_count=12&hide=nix,javascript,c%23,css,scss,html&exclude_repo=jikan,1blu-svelte-mail-setup,mail-setup-euromet,dots,nxvim&theme=github_dark_dimmed"
      - name: Update svg
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update stats
